export const API = Object.freeze({
	auth: {
		signIn: `auth/sign-in` as const,
		signUp: `auth/sign-up` as const,
		refresh: `auth/refresh` as const,
		signOut: `auth/sign-out` as const,
	},
	users: {
		base: 'users' as const,
		confirm: 'users/confirm' as const,
		recovery: 'users/recovery' as const,
		info: 'users/info' as const,
		managers: 'users/managers' as const,
		changeManager: 'users/manager/change' as const,
	},
	files: 'files' as const,
	feedback: 'feedback' as const,
	analytics: {
		base: 'analytics' as const,
		orders: 'analytics/orders' as const,
		ordersCount: 'analytics/orders/count' as const,
		ordersStats: {
			base: 'analytics/orders/stats' as const,
			grouped: 'analytics/orders/stats/grouped' as const,
		},
		users: {
			base: 'analytics/users' as const,
			info: 'analytics/users/info' as const,
			stats: 'analytics/users/stats' as const,
		},
	},
	orders: {
		base: 'orders' as const,
		current: 'orders/current' as const,
		all: 'orders/all' as const,
		save: 'orders/save' as const,
		copy: 'orders/copy' as const,
		info: 'orders/info' as const,
		last: 'orders/last' as const,
		number: 'orders/number' as const,
		count: 'orders/count' as const,
		manager: 'orders/by-manager' as const,
		finish: 'orders/finish' as const,
		changeManager: 'orders/manager/change' as const,
		download: 'orders/:id/download' as const,
	},
	positions: {
		base: 'orders/positions' as const,
		// data: 'orders/positions/data' as const,
		copy: 'orders/positions/copy' as const,
	},
	fastenings: 'fastenings' as const,
	snp: {
		base: 'snp' as const,
		data: 'snp/data' as const,
		info: 'snp/info' as const,
		standards: 'snp/standard-info' as const,
		types: 'snp/types' as const,
		fillers: 'snp/fillers' as const,
		materials: 'snp/materials' as const,
		sizes: 'snp/sizes' as const,
	},
	putg: {
		base: 'putg' as const,
		data: 'putg/data' as const,
		info: {
			base: 'putg/info' as const,
			filler: 'putg/info/by-filler' as const,
		},
		configurations: 'putg/configurations' as const,
		standards: 'putg/standard-info' as const,
		flangeTypes: 'putg/flange-types' as const,
		types: 'putg/types' as const,
		constructions: 'putg/constructions' as const,
		fillers: 'putg/fillers' as const,
		materials: 'putg/materials' as const,
		sizes: 'putg/sizes' as const,
	},
	wave: {
		standards: 'wave/standard-info' as const,
		flangeTypes: 'wave/flange-types' as const,
		types: 'wave/types' as const,
		constructions: 'wave/constructions' as const,
	},
})
