log_level: debug
log_source: false

http:
    serviceName: 'api-service'
    host: pro.sealur.ru
    port: 8080
    maxHeaderBytes: 1
    readTimeout: 10s
    writeTimeout: 10s
    domain: http://pro.sealur.ru
    link: http://pro.sealur.ru

cache:
    ttl: 3600s

auth:
    accessTokenTTL: 20m
    refreshTokenTTL: 24h
    limitAuthTTL: 30m
    countAttempt: 5
    confirmTTL: 1h
    secure: false
    domain: pro.sealur.ru

redis:
    host: 192.168.5.159
    port: 6379
    db: 0

limiter:
    rps: 10
    burst: 20
    ttl: 10m
